/*
 * Copyright 2019 xuelf.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.lifxue.cointda.pool;

/**
 *
 * @author xuelf
 */
public class InitTable {

    /**
     * Creates a new instance of InitTable
     */
    public InitTable() {

    }

    /**
     * 初始化数据库
     *
     *
     */
    public static void createTable() {
        //DerbyJdbcDao dbjd = DerbyJdbcDao.getInstance();
        String sql = "";

        ////////////////////////////////
//        sql = "drop table tab_curuse_coin";
//        DBUtilsHelper.dropTable(sql);
//        sql = "drop table tab_trade_data";
//        DBUtilsHelper.dropTable(sql);
//        sql = "drop table TAB_CoinMarketCap_id_map";
//        DBUtilsHelper.dropTable(sql);
//        sql = "drop table TAB_CoinMarketCap_listings";
//        DBUtilsHelper.dropTable(sql);
        /////////////////////////////////////
        //当前使用的交易品种
        if (!DBUtilsHelper.doesTableExist("tab_curuse_coin")) {
            sql = "CREATE TABLE tab_curuse_coin ("
                    + "id integer NOT NULL,"
                    + "symbol VARCHAR(20),"
                    + "cmc_rank integer,"
                    + "lastUpdated VARCHAR(100),"
                    + "primary key (id))";
            DBUtilsHelper.createTable(sql);
        }
        //交易数据表
        if (!DBUtilsHelper.doesTableExist("tab_trade_data")) {
            sql = "CREATE TABLE tab_trade_data ("
                    + "id int generated by default as identity,"
                    + "coin_id int NOT NULL,"
                    + "coin_symbol VARCHAR(20) NOT NULL,"
                    + "sale_or_buy VARCHAR(10) NOT NULL,"
                    + "price  DECIMAL(23,8) NOT NULL,"
                    + "num  DECIMAL(23,8) NOT NULL,"
                    + "total_price  DECIMAL(23,8) NOT NULL,"
                    + "trade_date VARCHAR(100) NOT NULL,"
                    + "primary key (id))";
            DBUtilsHelper.createTable(sql);
        }
        //品种信息
//        sql = "CREATE TABLE TAB_CoinMarketCap_id_map  ("
//                + "c_id integer NOT NULL,"
//                + "name VARCHAR(100) NOT NULL,"
//                + "symbol VARCHAR(20) NOT NULL,"
//                + "slug VARCHAR(100) NOT NULL,"
//                + "is_active integer NOT NULL,"
//                + "rank integer,"
//                + "first_historical_data VARCHAR(100),"
//                + "last_historical_data VARCHAR(100),"
//                + "p_id integer,"
//                + "token_address VARCHAR(100),"
//                + "primary key (c_id))";
//        DBUtilsHelper.createTable(sql);

        //最新品种价格表
        if (!DBUtilsHelper.doesTableExist("tab_CoinMarketCap_listings")) {
            sql = "CREATE TABLE tab_CoinMarketCap_listings  ("
                    + "id integer NOT NULL,"
                    + "name VARCHAR(100),"
                    + "symbol VARCHAR(20),"
                    + "slug VARCHAR(100),"
                    + "cmc_rank integer,"
                    + "date_added VARCHAR(100),"
                    + "platform_id integer,"
                    + "token_address VARCHAR(100),"
                    + "numMarketPairs integer,"
                    + "maxSupply DECIMAL(23,8),"
                    + "circulatingSupply DECIMAL(23,8),"
                    + "totalSupply DECIMAL(23,8),"
                    + "price DECIMAL(23,8),"
                    + "volume_24h DECIMAL(23,8),"
                    + "percent_change_1h DECIMAL(23,8),"
                    + "percent_change_24h DECIMAL(23,8),"
                    + "percent_change_7d DECIMAL(23,8),"
                    + "marketCap DECIMAL(23,8),"
                    + "lastUpdated VARCHAR(100),"
                    + "primary key (id))";
            DBUtilsHelper.createTable(sql);
        }
        /*
        sql = "CREATE TABLE TAB_COLORTYPE_CONTENT ("
                + "SEHAO_ID integer NOT NULL,"
                + "CAILIAO_ID integer NOT NULL,"
                + "CTC_NAME VARCHAR(100) NOT NULL,"
                + "CTC_NUM DECIMAL(10,5) NOT NULL,"
                + "CTC_NUMTYPE VARCHAR(100) NOT NULL,"
                + "CTC_ORD integer NOT NULL, "
                + "primary key (SEHAO_ID,CAILIAO_ID))";
        dbjd.createTable(sql);//色号所用材料表

        sql = "CREATE TABLE TAB_USER ("
                + "USER_ID integer NOT NULL,"
                + "USER_CODE VARCHAR(100) NOT NULL,"
                + "USER_NAME VARCHAR(100) NOT NULL,"
                + "USER_PW VARCHAR(100) NOT NULL,"
                + "USER_TYPE VARCHAR(20) NOT NULL, "
                + "primary key (USER_ID))";
        dbjd.createTable(sql);//用户表

        sql = "CREATE TABLE TAB_CUSTOMER ("
                + "CUSTOMER_ID integer NOT NULL,"
                + "CUSTOMER_NAME VARCHAR(160) NOT NULL,"
                + "CUSTOMER_PERSON VARCHAR(20),"
                + "CUSTOMER_PHONE VARCHAR(26),"
                + "CUSTOMER_MOBILEPHONE VARCHAR(22),"
                + "CUSTOMER_EMAIL VARCHAR(100),"
                + "CUSTOMER_ADDRESS VARCHAR(200),"
                + "CUSTOMER_POSTCODE VARCHAR(12),"
                + "primary key (CUSTOMER_ID))";
        dbjd.createTable(sql);//客户表

        sql = "CREATE TABLE TAB_SAFE ("
                + "SAFE_ID int generated by default as identity,"
                + "SAFE_NETNAME VARCHAR(160) NOT NULL,"
                + "SAFE_MAC VARCHAR(160) NOT NULL,"
                + "primary key (SAFE_ID))";
        dbjd.createTable(sql);//安全表

        sql = "CREATE TABLE TAB_COMPANYINFO ("
                + "COMPANYINFO_ID integer NOT NULL,"
                + "COMPANYINFO_NAME VARCHAR(160) NOT NULL,"
                + "COMPANYINFO_PERSON VARCHAR(20),"
                + "COMPANYINFO_PHONE VARCHAR(26),"
                + "COMPANYINFO_MOBILEPHONE VARCHAR(22),"
                + "COMPANYINFO_EMAIL VARCHAR(100),"
                + "COMPANYINFO_ADDRESS VARCHAR(200),"
                + "COMPANYINFO_POSTCODE VARCHAR(12),"
                + "primary key (COMPANYINFO_ID))";
        dbjd.createTable(sql);//公司信息打印设置表

        sql = "CREATE TABLE TAB_JSD("
                + "JSD_ID  integer NOT NULL,"
                + "JSD_CUSTOMERNAME VARCHAR(20) NOT NULL,"
                + "JSD_KAIPIAONAME VARCHAR(20) NOT NULL,"
                + "JSD_TIME DATE NOT NULL,"
                + "JSD_SONGHUONAME VARCHAR(20) NOT NULL,"
                + "JSD_CHEHAO VARCHAR(20) NOT NULL,"
                + "JSD_ALLZL VARCHAR(20) NOT NULL,"
                + "JSD_ALLJINE VARCHAR(20) NOT NULL,"
                + "JSD_ALLPISHU VARCHAR(20) NOT NULL,"
                + "JSD_CNAME VARCHAR(100) NOT NULL,"
                + "primary key (JSD_ID))";
        dbjd.createTable(sql);//织染费结算表

        sql = "CREATE TABLE TAB_JSDTABLE("
                + "JSDTABLE_ID  integer NOT NULL,"
                + "JSD_ID  integer NOT NULL,"
                + "JSDTABLE_GUOHAO VARCHAR(20) NOT NULL,"
                + "JSDTABLE_SEHAO VARCHAR(40) NOT NULL,"
                + "JSDTABLE_DANJIA VARCHAR(20) NOT NULL,"
                + "JSDTABLE_ZHONGLIANG VARCHAR(20) NOT NULL,"
                + "JSDTABLE_JINE VARCHAR(20) NOT NULL,"
                + "JSDTABLE_PISHU VARCHAR(20) NOT NULL,"
                + "JSDTABLE_BEIZHU VARCHAR(400) NOT NULL,"
                + "primary key (JSDTABLE_ID))";
        dbjd.createTable(sql);//--织染费结算表格内容表

        sql = "CREATE TABLE TAB_PRODUCECONTROL("
                + "PRODUCECONTROL_ID  integer NOT NULL,"
                + "PRODUCECONTROL_CUSTOMER VARCHAR(160) NOT NULL,"
                + "PRODUCECONTROL_GUOHAO VARCHAR(40) NOT NULL,"
                + "PRODUCECONTROL_SEHAO VARCHAR(40) NOT NULL,"
                + "PRODUCECONTROL_PINZHONG VARCHAR(20) NOT NULL,"
                + "PRODUCECONTROL_JIHUAHAO VARCHAR(20) NOT NULL,"
                + "PRODUCECONTROL_ALLPISHU VARCHAR(20) NOT NULL,"
                + "PRODUCECONTROL_ALLZHONGLIANG VARCHAR(20) NOT NULL,"
                + "PRODUCECONTROL_COMPANY VARCHAR(200) NOT NULL,"
                + "PRODUCECONTROL_USER VARCHAR(20) NOT NULL,"
                + "PRODUCECONTROL_PHONE VARCHAR(50) NOT NULL,"
                + "PRODUCECONTROL_DATE DATE NOT NULL,"
                + "PRODUCECONTROL_BEIZHU VARCHAR(400) NOT NULL,"
                + "primary key (PRODUCECONTROL_ID))";
        dbjd.createTable(sql);//--生产调度单

        sql = "CREATE TABLE TAB_PCCONTENT("
                + "PCCONTENT_ID  integer NOT NULL,"
                + "PRODUCECONTROL_ID  integer NOT NULL,"
                + "PCCONTENT_PISHU VARCHAR(20) NOT NULL,"
                + "PCCONTENT_GUIGE VARCHAR(20) NOT NULL,"
                + "PCCONTENT_ZHONGLIANG VARCHAR(20) NOT NULL,"
                + "primary key (PCCONTENT_ID))";
        dbjd.createTable(sql);//--生产调度单 内容表
         */
        ///////////////////////////////////
        //sql = "insert into TAB_USER values (0,'admin','admin','admin','admin')";
        //dbjd.insert(sql);
    }

    /**
     *
     * @param args
     */
    public static void main(String[] args) {
        InitTable.createTable();
    }
}
