/*
 * Copyright 2019 xuelf.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.lifxue.cointda.dao.jdbc;


/**
 *
 * @author xuelf
 */
public class InitTable {

    /**
     * Creates a new instance of InitTable
     */
    public InitTable() {
        
    }

    /**
     * 初始化数据库
     *
     *
     */
    public void createTable() {
        DerbyJdbcDao dbjd = DerbyJdbcDao.getInstance();
        String sql = "";

        ////////////////////////////////
        sql = "drop table TAB_COINTYPE";
        dbjd.dropTable(sql);

        /////////////////////////////////////
        sql = "CREATE TABLE TAB_COINTYPE ("
                + "SHORT_NAME VARCHAR(10) NOT NULL,"
                + "FULL_NAME VARCHAR(100) NOT NULL,"
                + "CN_NAME VARCHAR(100) NOT NULL,"
                + "primary key (SHORT_NAME))";
        dbjd.createTable(sql);
        /*
        sql = "CREATE TABLE TAB_COLORTYPE_CONTENT ("
                + "SEHAO_ID integer NOT NULL,"
                + "CAILIAO_ID integer NOT NULL,"
                + "CTC_NAME VARCHAR(100) NOT NULL,"
                + "CTC_NUM DECIMAL(10,5) NOT NULL,"
                + "CTC_NUMTYPE VARCHAR(100) NOT NULL,"
                + "CTC_ORD integer NOT NULL, "
                + "primary key (SEHAO_ID,CAILIAO_ID))";
        dbjd.createTable(sql);//色号所用材料表

        sql = "CREATE TABLE TAB_USER ("
                + "USER_ID integer NOT NULL,"
                + "USER_CODE VARCHAR(100) NOT NULL,"
                + "USER_NAME VARCHAR(100) NOT NULL,"
                + "USER_PW VARCHAR(100) NOT NULL,"
                + "USER_TYPE VARCHAR(20) NOT NULL, "
                + "primary key (USER_ID))";
        dbjd.createTable(sql);//用户表

        sql = "CREATE TABLE TAB_CUSTOMER ("
                + "CUSTOMER_ID integer NOT NULL,"
                + "CUSTOMER_NAME VARCHAR(160) NOT NULL,"
                + "CUSTOMER_PERSON VARCHAR(20),"
                + "CUSTOMER_PHONE VARCHAR(26),"
                + "CUSTOMER_MOBILEPHONE VARCHAR(22),"
                + "CUSTOMER_EMAIL VARCHAR(100),"
                + "CUSTOMER_ADDRESS VARCHAR(200),"
                + "CUSTOMER_POSTCODE VARCHAR(12),"
                + "primary key (CUSTOMER_ID))";
        dbjd.createTable(sql);//客户表

        sql = "CREATE TABLE TAB_SAFE ("
                + "SAFE_ID int generated by default as identity,"
                + "SAFE_NETNAME VARCHAR(160) NOT NULL,"
                + "SAFE_MAC VARCHAR(160) NOT NULL,"
                + "primary key (SAFE_ID))";
        dbjd.createTable(sql);//安全表

        sql = "CREATE TABLE TAB_COMPANYINFO ("
                + "COMPANYINFO_ID integer NOT NULL,"
                + "COMPANYINFO_NAME VARCHAR(160) NOT NULL,"
                + "COMPANYINFO_PERSON VARCHAR(20),"
                + "COMPANYINFO_PHONE VARCHAR(26),"
                + "COMPANYINFO_MOBILEPHONE VARCHAR(22),"
                + "COMPANYINFO_EMAIL VARCHAR(100),"
                + "COMPANYINFO_ADDRESS VARCHAR(200),"
                + "COMPANYINFO_POSTCODE VARCHAR(12),"
                + "primary key (COMPANYINFO_ID))";
        dbjd.createTable(sql);//公司信息打印设置表

        sql = "CREATE TABLE TAB_JSD("
                + "JSD_ID  integer NOT NULL,"
                + "JSD_CUSTOMERNAME VARCHAR(20) NOT NULL,"
                + "JSD_KAIPIAONAME VARCHAR(20) NOT NULL,"
                + "JSD_TIME DATE NOT NULL,"
                + "JSD_SONGHUONAME VARCHAR(20) NOT NULL,"
                + "JSD_CHEHAO VARCHAR(20) NOT NULL,"
                + "JSD_ALLZL VARCHAR(20) NOT NULL,"
                + "JSD_ALLJINE VARCHAR(20) NOT NULL,"
                + "JSD_ALLPISHU VARCHAR(20) NOT NULL,"
                + "JSD_CNAME VARCHAR(100) NOT NULL,"
                + "primary key (JSD_ID))";
        dbjd.createTable(sql);//织染费结算表

        sql = "CREATE TABLE TAB_JSDTABLE("
                + "JSDTABLE_ID  integer NOT NULL,"
                + "JSD_ID  integer NOT NULL,"
                + "JSDTABLE_GUOHAO VARCHAR(20) NOT NULL,"
                + "JSDTABLE_SEHAO VARCHAR(40) NOT NULL,"
                + "JSDTABLE_DANJIA VARCHAR(20) NOT NULL,"
                + "JSDTABLE_ZHONGLIANG VARCHAR(20) NOT NULL,"
                + "JSDTABLE_JINE VARCHAR(20) NOT NULL,"
                + "JSDTABLE_PISHU VARCHAR(20) NOT NULL,"
                + "JSDTABLE_BEIZHU VARCHAR(400) NOT NULL,"
                + "primary key (JSDTABLE_ID))";
        dbjd.createTable(sql);//--织染费结算表格内容表

        sql = "CREATE TABLE TAB_PRODUCECONTROL("
                + "PRODUCECONTROL_ID  integer NOT NULL,"
                + "PRODUCECONTROL_CUSTOMER VARCHAR(160) NOT NULL,"
                + "PRODUCECONTROL_GUOHAO VARCHAR(40) NOT NULL,"
                + "PRODUCECONTROL_SEHAO VARCHAR(40) NOT NULL,"
                + "PRODUCECONTROL_PINZHONG VARCHAR(20) NOT NULL,"
                + "PRODUCECONTROL_JIHUAHAO VARCHAR(20) NOT NULL,"
                + "PRODUCECONTROL_ALLPISHU VARCHAR(20) NOT NULL,"
                + "PRODUCECONTROL_ALLZHONGLIANG VARCHAR(20) NOT NULL,"
                + "PRODUCECONTROL_COMPANY VARCHAR(200) NOT NULL,"
                + "PRODUCECONTROL_USER VARCHAR(20) NOT NULL,"
                + "PRODUCECONTROL_PHONE VARCHAR(50) NOT NULL,"
                + "PRODUCECONTROL_DATE DATE NOT NULL,"
                + "PRODUCECONTROL_BEIZHU VARCHAR(400) NOT NULL,"
                + "primary key (PRODUCECONTROL_ID))";
        dbjd.createTable(sql);//--生产调度单

        sql = "CREATE TABLE TAB_PCCONTENT("
                + "PCCONTENT_ID  integer NOT NULL,"
                + "PRODUCECONTROL_ID  integer NOT NULL,"
                + "PCCONTENT_PISHU VARCHAR(20) NOT NULL,"
                + "PCCONTENT_GUIGE VARCHAR(20) NOT NULL,"
                + "PCCONTENT_ZHONGLIANG VARCHAR(20) NOT NULL,"
                + "primary key (PCCONTENT_ID))";
        dbjd.createTable(sql);//--生产调度单 内容表
         */
        ///////////////////////////////////
        //sql = "insert into TAB_USER values (0,'admin','admin','admin','admin')";
        //dbjd.insert(sql);

    }

    /**
     *
     * @param args
     */
    public static void main(String[] args) {
        InitTable initTable = new InitTable();
        initTable.createTable();
    }
}
